from typing import TypedDict, Optional, List


class AgentState(TypedDict):
    image_path: str

    # generated by orchestrator
    image_hash: Optional[str]

    user_prompt: str
    detailed: bool

    # vision output
    description: Optional[str]

    # tts output
    audio_path: Optional[str]

    history: List[str]

    # better for graph routing
    valid_image: Optional[bool]

    error: Optional[str]